// ARM Template Generator for Azure Architecture
// Converts visual architecture design to Azure Resource Manager templates

/**
 * Generate ARM Template from architecture items and connections
 * @param {Array} items - Array of Azure service items on canvas
 * @param {Array} connections - Array of connections between items
 * @param {Object} options - Optional: compliance, branding, author, version, timestamp
 * @returns {Object} - Complete ARM template JSON
 */
export const generateARMTemplate = (items, connections, options = {}) => {
  const {
    complianceSummary = {},
    branding = "Arunim's IT Caffe",
    author = 'Arunim Pandey',
    version = '2.1.0',
    timestamp = new Date().toISOString(),
    complianceBadge = '🟢',
  } = options;

  const template = {
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "metadata": {
      "description": "Azure Architecture - Generated by Azure Architecture Designer",
      "branding": branding,
      "complianceBadge": complianceBadge,
      "complianceSummary": complianceSummary,
      "version": version,
      "author": author,
      "timestamp": timestamp,
      "generatedDate": timestamp
    },
    "parameters": {
      "location": {
        "type": "string",
        "defaultValue": "[resourceGroup().location]",
        "metadata": {
          "description": "Location for all resources"
        }
      },
      "environment": {
        "type": "string",
        "defaultValue": "production",
        "allowedValues": ["development", "staging", "production"],
        "metadata": {
          "description": "Environment name"
        }
      }
    },
    "variables": {
      "resourcePrefix": "[concat('azure-arch-', parameters('environment'))]"
    },
    "resources": [],
    "outputs": {}
  };
  
  // Generate resources for each item
  items.forEach((item, index) => {
    const resources = generateARMResource(item, index);
    if (resources) {
      if (Array.isArray(resources)) {
        template.resources.push(...resources);
      } else {
        template.resources.push(resources);
      }
    }
    
    // Generate outputs
    const output = generateARMOutput(item, index);
    if (output) {
      template.outputs[`${item.serviceType}_${index}`] = output;
    }
  });
  
  return template;
};

/**
 * Generate ARM resource for a specific Azure service
 */
const generateARMResource = (item, index) => {
  const serviceName = item.name.toLowerCase().replace(/\s+/g, '-');
  const resourceName = `${serviceName}-${index}`;
  
  const resources = {
    // Compute
    vm: [
      {
        "type": "Microsoft.Network/networkInterfaces",
        "apiVersion": "2023-04-01",
        "name": `${resourceName}-nic`,
        "location": "[parameters('location')]",
        "properties": {
          "ipConfigurations": [
            {
              "name": "ipconfig1",
              "properties": {
                "subnet": {
                  "id": "[resourceId('Microsoft.Network/virtualNetworks/subnets', 'vnet-main', 'default')]"
                },
                "privateIPAllocationMethod": "Dynamic"
              }
            }
          ]
        }
      },
      {
        "type": "Microsoft.Compute/virtualMachines",
        "apiVersion": "2023-03-01",
        "name": resourceName,
        "location": "[parameters('location')]",
        "dependsOn": [
          `[resourceId('Microsoft.Network/networkInterfaces', '${resourceName}-nic')]`
        ],
        "properties": {
          "hardwareProfile": {
            "vmSize": "Standard_B2s"
          },
          "storageProfile": {
            "imageReference": {
              "publisher": "Canonical",
              "offer": "0001-com-ubuntu-server-jammy",
              "sku": "22_04-lts",
              "version": "latest"
            },
            "osDisk": {
              "createOption": "FromImage",
              "managedDisk": {
                "storageAccountType": "Standard_LRS"
              }
            }
          },
          "osProfile": {
            "computerName": resourceName,
            "adminUsername": "azureuser",
            "adminPassword": "P@ssw0rd1234!",
            "linuxConfiguration": {
              "disablePasswordAuthentication": false
            }
          },
          "networkProfile": {
            "networkInterfaces": [
              {
                "id": `[resourceId('Microsoft.Network/networkInterfaces', '${resourceName}-nic')]`
              }
            ]
          }
        },
        "tags": {
          "environment": "[parameters('environment')]",
          "createdBy": "azure-architecture-designer"
        }
      }
    ],

    vmss: {
      "type": "Microsoft.Compute/virtualMachineScaleSets",
      "apiVersion": "2023-03-01",
      "name": resourceName,
      "location": "[parameters('location')]",
      "sku": {
        "name": "Standard_B2s",
        "tier": "Standard",
        "capacity": 2
      },
      "properties": {
        "overprovision": true,
        "upgradePolicy": {
          "mode": "Manual"
        },
        "virtualMachineProfile": {
          "storageProfile": {
            "imageReference": {
              "publisher": "Canonical",
              "offer": "0001-com-ubuntu-server-jammy",
              "sku": "22_04-lts",
              "version": "latest"
            },
            "osDisk": {
              "createOption": "FromImage",
              "caching": "ReadWrite"
            }
          },
          "osProfile": {
            "computerNamePrefix": resourceName,
            "adminUsername": "azureuser",
            "adminPassword": "P@ssw0rd1234!"
          },
          "networkProfile": {
            "networkInterfaceConfigurations": [
              {
                "name": `${resourceName}-nic`,
                "properties": {
                  "primary": true,
                  "ipConfigurations": [
                    {
                      "name": "ipconfig1",
                      "properties": {
                        "subnet": {
                          "id": "[resourceId('Microsoft.Network/virtualNetworks/subnets', 'vnet-main', 'default')]"
                        }
                      }
                    }
                  ]
                }
              }
            ]
          }
        }
      }
    },

    function: [
      {
        "type": "Microsoft.Storage/storageAccounts",
        "apiVersion": "2023-01-01",
        "name": resourceName.replace(/-/g, '') + 'sa',
        "location": "[parameters('location')]",
        "sku": {
          "name": "Standard_LRS"
        },
        "kind": "StorageV2"
      },
      {
        "type": "Microsoft.Web/serverfarms",
        "apiVersion": "2022-09-01",
        "name": `${resourceName}-plan`,
        "location": "[parameters('location')]",
        "sku": {
          "name": "Y1",
          "tier": "Dynamic"
        },
        "properties": {}
      },
      {
        "type": "Microsoft.Web/sites",
        "apiVersion": "2022-09-01",
        "name": resourceName,
        "location": "[parameters('location')]",
        "kind": "functionapp,linux",
        "dependsOn": [
          `[resourceId('Microsoft.Web/serverfarms', '${resourceName}-plan')]`,
          `[resourceId('Microsoft.Storage/storageAccounts', '${resourceName.replace(/-/g, '')}sa')]`
        ],
        "properties": {
          "serverFarmId": `[resourceId('Microsoft.Web/serverfarms', '${resourceName}-plan')]`,
          "siteConfig": {
            "appSettings": [
              {
                "name": "AzureWebJobsStorage",
                "value": `[concat('DefaultEndpointsProtocol=https;AccountName=', '${resourceName.replace(/-/g, '')}sa', ';AccountKey=', listKeys(resourceId('Microsoft.Storage/storageAccounts', '${resourceName.replace(/-/g, '')}sa'), '2023-01-01').keys[0].value)]`
              },
              {
                "name": "FUNCTIONS_EXTENSION_VERSION",
                "value": "~4"
              },
              {
                "name": "FUNCTIONS_WORKER_RUNTIME",
                "value": "node"
              }
            ]
          }
        }
      }
    ],

    appservice: [
      {
        "type": "Microsoft.Web/serverfarms",
        "apiVersion": "2022-09-01",
        "name": `${resourceName}-plan`,
        "location": "[parameters('location')]",
        "sku": {
          "name": "B1",
          "tier": "Basic"
        },
        "kind": "linux",
        "properties": {
          "reserved": true
        }
      },
      {
        "type": "Microsoft.Web/sites",
        "apiVersion": "2022-09-01",
        "name": resourceName,
        "location": "[parameters('location')]",
        "dependsOn": [
          `[resourceId('Microsoft.Web/serverfarms', '${resourceName}-plan')]`
        ],
        "properties": {
          "serverFarmId": `[resourceId('Microsoft.Web/serverfarms', '${resourceName}-plan')]`,
          "siteConfig": {
            "linuxFxVersion": "NODE|18-lts"
          }
        }
      }
    ],

    aks: {
      "type": "Microsoft.ContainerService/managedClusters",
      "apiVersion": "2023-07-01",
      "name": resourceName,
      "location": "[parameters('location')]",
      "identity": {
        "type": "SystemAssigned"
      },
      "properties": {
        "dnsPrefix": resourceName,
        "agentPoolProfiles": [
          {
            "name": "agentpool",
            "count": 2,
            "vmSize": "Standard_B2s",
            "mode": "System"
          }
        ]
      }
    },

    // Storage
    storage: {
      "type": "Microsoft.Storage/storageAccounts",
      "apiVersion": "2023-01-01",
      "name": resourceName.replace(/-/g, '') + 'sa',
      "location": "[parameters('location')]",
      "sku": {
        "name": "Standard_LRS"
      },
      "kind": "StorageV2",
      "properties": {
        "supportsHttpsTrafficOnly": true,
        "minimumTlsVersion": "TLS1_2"
      }
    },

    // Databases
    sqldb: [
      {
        "type": "Microsoft.Sql/servers",
        "apiVersion": "2022-05-01-preview",
        "name": `${resourceName}-server`,
        "location": "[parameters('location')]",
        "properties": {
          "administratorLogin": "sqladmin",
          "administratorLoginPassword": "P@ssw0rd1234!",
          "version": "12.0"
        }
      },
      {
        "type": "Microsoft.Sql/servers/databases",
        "apiVersion": "2022-05-01-preview",
        "name": `${resourceName}-server/${resourceName}-db`,
        "location": "[parameters('location')]",
        "dependsOn": [
          `[resourceId('Microsoft.Sql/servers', '${resourceName}-server')]`
        ],
        "sku": {
          "name": "Basic",
          "tier": "Basic"
        },
        "properties": {
          "collation": "SQL_Latin1_General_CP1_CI_AS",
          "maxSizeBytes": 2147483648
        }
      }
    ],

    cosmosdb: {
      "type": "Microsoft.DocumentDB/databaseAccounts",
      "apiVersion": "2023-04-15",
      "name": resourceName,
      "location": "[parameters('location')]",
      "kind": "GlobalDocumentDB",
      "properties": {
        "databaseAccountOfferType": "Standard",
        "locations": [
          {
            "locationName": "[parameters('location')]",
            "failoverPriority": 0
          }
        ],
        "consistencyPolicy": {
          "defaultConsistencyLevel": "Session"
        }
      }
    },

    // Networking
    vnet: [
      {
        "type": "Microsoft.Network/virtualNetworks",
        "apiVersion": "2023-04-01",
        "name": resourceName,
        "location": "[parameters('location')]",
        "properties": {
          "addressSpace": {
            "addressPrefixes": ["10.0.0.0/16"]
          },
          "subnets": [
            {
              "name": "default",
              "properties": {
                "addressPrefix": "10.0.1.0/24"
              }
            }
          ]
        }
      }
    ],

    loadbalancer: [
      {
        "type": "Microsoft.Network/publicIPAddresses",
        "apiVersion": "2023-04-01",
        "name": `${resourceName}-pip`,
        "location": "[parameters('location')]",
        "sku": {
          "name": "Standard"
        },
        "properties": {
          "publicIPAllocationMethod": "Static"
        }
      },
      {
        "type": "Microsoft.Network/loadBalancers",
        "apiVersion": "2023-04-01",
        "name": resourceName,
        "location": "[parameters('location')]",
        "sku": {
          "name": "Standard"
        },
        "dependsOn": [
          `[resourceId('Microsoft.Network/publicIPAddresses', '${resourceName}-pip')]`
        ],
        "properties": {
          "frontendIPConfigurations": [
            {
              "name": "LoadBalancerFrontEnd",
              "properties": {
                "publicIPAddress": {
                  "id": `[resourceId('Microsoft.Network/publicIPAddresses', '${resourceName}-pip')]`
                }
              }
            }
          ],
          "backendAddressPools": [
            {
              "name": "BackendPool1"
            }
          ]
        }
      }
    ],

    // Security
    keyvault: {
      "type": "Microsoft.KeyVault/vaults",
      "apiVersion": "2023-02-01",
      "name": resourceName,
      "location": "[parameters('location')]",
      "properties": {
        "tenantId": "[subscription().tenantId]",
        "sku": {
          "family": "A",
          "name": "standard"
        },
        "accessPolicies": []
      }
    },

    // Monitoring
    monitor: {
      "type": "Microsoft.OperationalInsights/workspaces",
      "apiVersion": "2022-10-01",
      "name": resourceName,
      "location": "[parameters('location')]",
      "properties": {
        "sku": {
          "name": "PerGB2018"
        },
        "retentionInDays": 30
      }
    },

    appinsights: {
      "type": "Microsoft.Insights/components",
      "apiVersion": "2020-02-02",
      "name": resourceName,
      "location": "[parameters('location')]",
      "kind": "web",
      "properties": {
        "Application_Type": "web"
      }
    }
  };
  
  return resources[item.serviceType] || null;
};

/**
 * Generate ARM output for a resource
 */
const generateARMOutput = (item, index) => {
  const serviceName = item.name.toLowerCase().replace(/\s+/g, '-');
  const resourceName = `${serviceName}-${index}`;
  
  const outputs = {
    vm: {
      "type": "string",
      "value": `[reference(resourceId('Microsoft.Network/networkInterfaces', '${resourceName}-nic')).ipConfigurations[0].properties.privateIPAddress]`
    },
    storage: {
      "type": "string",
      "value": `[reference(resourceId('Microsoft.Storage/storageAccounts', '${resourceName.replace(/-/g, '')}sa')).primaryEndpoints.blob]`
    },
    sqldb: {
      "type": "string",
      "value": `[reference(resourceId('Microsoft.Sql/servers', '${resourceName}-server')).fullyQualifiedDomainName]`
    }
  };
  
  return outputs[item.serviceType] || null;
};

/**
 * Download ARM Template as JSON file
 */
export const downloadARMTemplate = (items, connections) => {
  const template = generateARMTemplate(items, connections);
  const json = JSON.stringify(template, null, 2);
  const blob = new Blob([json], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `azure-architecture-arm-${Date.now()}.json`;
  link.click();
  URL.revokeObjectURL(url);
};
