// Bicep Template Generator
// Generates Azure Bicep (.bicep) files from canvas items
// Bicep is the modern replacement for ARM JSON templates

const RESOURCE_TYPE_MAP = {
  'Virtual Machine': { type: 'Microsoft.Compute/virtualMachines', apiVersion: '2023-09-01' },
  'App Service': { type: 'Microsoft.Web/sites', apiVersion: '2023-01-01' },
  'Function App': { type: 'Microsoft.Web/sites', apiVersion: '2023-01-01', kind: 'functionapp' },
  'SQL Database': { type: 'Microsoft.Sql/servers/databases', apiVersion: '2023-05-01-preview' },
  'Cosmos DB': { type: 'Microsoft.DocumentDB/databaseAccounts', apiVersion: '2023-11-15' },
  'Storage Account': { type: 'Microsoft.Storage/storageAccounts', apiVersion: '2023-01-01' },
  'Key Vault': { type: 'Microsoft.KeyVault/vaults', apiVersion: '2023-07-01' },
  'Application Gateway': { type: 'Microsoft.Network/applicationGateways', apiVersion: '2023-09-01' },
  'Azure Firewall': { type: 'Microsoft.Network/azureFirewalls', apiVersion: '2023-09-01' },
  'VPN Gateway': { type: 'Microsoft.Network/virtualNetworkGateways', apiVersion: '2023-09-01' },
  'Kubernetes Service': { type: 'Microsoft.ContainerService/managedClusters', apiVersion: '2023-10-01' },
  'Container Registry': { type: 'Microsoft.ContainerRegistry/registries', apiVersion: '2023-07-01' },
  'Service Bus': { type: 'Microsoft.ServiceBus/namespaces', apiVersion: '2022-10-01-preview' },
  'Event Hubs': { type: 'Microsoft.EventHub/namespaces', apiVersion: '2023-01-01-preview' },
  'API Management': { type: 'Microsoft.ApiManagement/service', apiVersion: '2023-05-01-preview' },
  'Azure Cache for Redis': { type: 'Microsoft.Cache/redis', apiVersion: '2023-08-01' },
  'Azure Databricks': { type: 'Microsoft.Databricks/workspaces', apiVersion: '2023-02-01' },
  'Azure Synapse Analytics': { type: 'Microsoft.Synapse/workspaces', apiVersion: '2021-06-01' },
  'Application Insights': { type: 'Microsoft.Insights/components', apiVersion: '2020-02-02' },
  'Azure Bastion': { type: 'Microsoft.Network/bastionHosts', apiVersion: '2023-09-01' },
  'Traffic Manager': { type: 'Microsoft.Network/trafficManagerProfiles', apiVersion: '2022-04-01' },
  'Data Factory': { type: 'Microsoft.DataFactory/factories', apiVersion: '2018-06-01' },
  'Data Lake Storage': { type: 'Microsoft.Storage/storageAccounts', apiVersion: '2023-01-01', kind: 'StorageV2', hns: true },
  'Power BI Embedded': { type: 'Microsoft.PowerBIDedicated/capacities', apiVersion: '2021-01-01' },
};

function sanitizeName(name) {
  return name.replace(/[^a-zA-Z0-9]/g, '').toLowerCase() || 'resource';
}

function generateResourceBlock(item, region) {
  const mapping = RESOURCE_TYPE_MAP[item.type] || null;
  if (!mapping) {
    return `// TODO: ${item.name} (${item.type}) — no Bicep mapping available\n`;
  }

  const varName = sanitizeName(item.name);
  let block = `resource ${varName} '${mapping.type}@${mapping.apiVersion}' = {\n`;
  block += `  name: '${varName}'\n`;
  block += `  location: location\n`;

  if (mapping.kind) {
    block += `  kind: '${mapping.kind}'\n`;
  }

  // Add minimal properties based on type
  block += `  properties: {}\n`;

  if (item.type === 'Storage Account' || mapping.type.includes('Storage')) {
    block = `resource ${varName} '${mapping.type}@${mapping.apiVersion}' = {\n`;
    block += `  name: '${varName}'\n`;
    block += `  location: location\n`;
    block += `  kind: '${mapping.kind || 'StorageV2'}'\n`;
    block += `  sku: {\n    name: 'Standard_LRS'\n  }\n`;
    block += `  properties: {${mapping.hns ? '\n    isHnsEnabled: true\n  ' : ''}}\n`;
  }

  block += `}\n`;
  return block;
}

export function generateBicep(items, connections, boundaries, options = {}) {
  const region = options.region || 'eastus';
  const lines = [];

  // Header
  lines.push('// Generated by Cloud Canvas Designer');
  lines.push(`// Date: ${new Date().toISOString()}`);
  lines.push(`// Services: ${items.length}, Connections: ${connections.length}`);
  lines.push('');

  // Target scope
  lines.push("targetScope = 'resourceGroup'");
  lines.push('');

  // Parameters
  lines.push("param location string = resourceGroup().location");
  lines.push("param environment string = 'production'");
  lines.push('');

  // Resources
  items.forEach(item => {
    lines.push(generateResourceBlock(item, region));
  });

  // Outputs
  lines.push('// Outputs');
  items.forEach(item => {
    const varName = sanitizeName(item.name);
    const mapping = RESOURCE_TYPE_MAP[item.type];
    if (mapping) {
      lines.push(`output ${varName}Id string = ${varName}.id`);
    }
  });

  return lines.join('\n');
}

export function exportBicepFile(items, connections, boundaries, options = {}) {
  const content = generateBicep(items, connections, boundaries, options);
  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, -5);
  link.href = url;
  link.download = `azure-architecture-${timestamp}.bicep`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);

  return {
    filename: link.download,
    itemCount: items.length,
    connectionCount: connections.length,
  };
}
