// Azure Cost Estimate PDF Generator
// Simple PDF generator for cost reports

import jsPDF from 'jspdf';
import { calculateCost, formatCost, azureRegions, currencies } from './costCalculator';

/**
 * Generate and download a professional PDF cost report
 * @param {Array} items - Array of Azure service items on canvas
 * @param {string} regionKey - Azure region key (default: 'eastus')
 * @param {string} currencyKey - Currency code (default: 'USD')
 */
export const generateCostPDF = (items, regionKey = 'eastus', currencyKey = 'USD') => {
  try {
    console.log('Starting PDF generation...');
    
    if (!items || items.length === 0) {
      throw new Error('No items to export');
    }    const costData = calculateCost(items, regionKey, currencyKey);
    const region = azureRegions[regionKey] || azureRegions['eastus'];
    const currency = currencies[currencyKey] || currencies['USD'];
    console.log('Cost data calculated:', costData);
    
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.width;
    const margin = 20;
    let y = 20;

    // HEADER
    doc.setFillColor(0, 120, 212);
    doc.rect(0, 0, pageWidth, 50, 'F');
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text('Azure Architecture Designer', margin, 20);
    
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text('Cost Estimation Report', margin, 30);
      doc.setFontSize(9);
    const reportDate = new Date().toLocaleDateString('en-US');
    const reportID = `COST-${Date.now().toString().slice(-8)}`;
    doc.text(`Date: ${reportDate}`, pageWidth - margin - 40, 20);
    doc.text(`ID: ${reportID}`, pageWidth - margin - 40, 27);
    doc.text(`Region: ${region.name}`, pageWidth - margin - 40, 34);
    doc.text(`Currency: ${currency.name}`, pageWidth - margin - 40, 41);
    
    y = 60;

    // COST SUMMARY
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('Cost Summary', margin, y);
    y += 10;
    
    doc.setDrawColor(220, 220, 220);
    doc.setLineWidth(0.5);
    doc.rect(margin, y, pageWidth - 2 * margin, 35);
      doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.text('Monthly Cost:', margin + 10, y + 12);
    
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 120, 212);
    doc.text(formatCost(costData.totalMonthly, currencyKey), pageWidth - margin - 10, y + 12, { align: 'right' });
    
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.text('Yearly Cost:', margin + 10, y + 25);
    
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text(formatCost(costData.totalYearly, currencyKey), pageWidth - margin - 10, y + 25, { align: 'right' });
    
    y += 45;

    // RESOURCES
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Resource Breakdown', margin, y);
    y += 8;
    
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    
    if (costData.breakdown && costData.breakdown.length > 0) {
      costData.breakdown.forEach((item, index) => {
        if (y > 270) {
          doc.addPage();
          y = 20;
        }
          doc.text(`${index + 1}. ${item.name}`, margin + 5, y);
        doc.text(`${item.serviceType}`, margin + 80, y);
        doc.text(formatCost(item.cost, currencyKey), pageWidth - margin - 10, y, { align: 'right' });
        y += 6;
      });
    }
    
    y += 10;

    // TOTAL
    doc.setDrawColor(0, 120, 212);
    doc.setLineWidth(1);
    doc.rect(pageWidth - margin - 70, y, 70, 25);
      doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text('TOTAL MONTHLY:', pageWidth - margin - 65, y + 10);
    doc.setFontSize(14);
    doc.setTextColor(0, 120, 212);
    doc.text(formatCost(costData.totalMonthly, currencyKey), pageWidth - margin - 5, y + 10, { align: 'right' });
    
    doc.setFontSize(9);
    doc.setTextColor(0, 0, 0);
    doc.text('TOTAL YEARLY:', pageWidth - margin - 65, y + 18);
    doc.setFontSize(12);
    doc.text(formatCost(costData.totalYearly, currencyKey), pageWidth - margin - 5, y + 18, { align: 'right' });

    // FOOTER
    doc.setFontSize(8);
    doc.setFont('helvetica', 'italic');
    doc.setTextColor(120, 120, 120);
    doc.text(`Estimate based on Azure pricing (February 2026, ${region.name})`, margin, 280);
    doc.text(`Currency: ${currency.name} (${currency.symbol})`, margin, 285);
    doc.text('Generated by Azure Architecture Designer', margin, 290);

    // Save
    const fileName = `Azure-Cost-Estimate-${Date.now()}.pdf`;
    doc.save(fileName);
    console.log('PDF saved:', fileName);
    
    return fileName;
  } catch (error) {
    console.error('PDF generation error:', error);
    throw error;
  }
};

export default generateCostPDF;
