// Terraform Configuration Generator for Azure Architecture
// Converts visual architecture design to Terraform .tf files

/**
 * Generate Terraform configuration from architecture items and connections
 * @param {Array} items - Array of Azure service items on canvas
 * @param {Array} connections - Array of connections between items
 * @returns {string} - Complete Terraform configuration
 */
export const generateTerraform = (items, connections) => {
  const config = [];
  
  // Header
  config.push(`# Azure Architecture - Terraform Configuration`);
  config.push(`# Generated by Azure Architecture Designer`);
  config.push(`# Date: ${new Date().toISOString()}\n`);
  
  // Provider configuration
  config.push(`terraform {`);
  config.push(`  required_providers {`);
  config.push(`    azurerm = {`);
  config.push(`      source  = "hashicorp/azurerm"`);
  config.push(`      version = "~> 3.0"`);
  config.push(`    }`);
  config.push(`  }`);
  config.push(`}\n`);
  
  config.push(`provider "azurerm" {`);
  config.push(`  features {}`);
  config.push(`}\n`);
  
  // Resource Group
  config.push(`resource "azurerm_resource_group" "main" {`);
  config.push(`  name     = "rg-azure-architecture"`);
  config.push(`  location = "East US"`);
  config.push(`}\n`);
  
  // Generate resources for each item
  items.forEach((item, index) => {
    const resourceConfig = generateResourceConfig(item, index);
    if (resourceConfig) {
      config.push(resourceConfig);
      config.push('');
    }
  });
  
  // Add networking resources if VNets exist
  const vnets = items.filter(item => item.serviceType === 'vnet');
  if (vnets.length > 0) {
    config.push(generateNetworkingConfig(items));
  }
  
  // Output values
  config.push(`# Outputs`);
  items.forEach((item, index) => {
    const output = generateOutput(item, index);
    if (output) {
      config.push(output);
    }
  });
  
  return config.join('\n');
};

/**
 * Generate Terraform resource configuration for a specific Azure service
 */
const generateResourceConfig = (item, index) => {
  const resourceName = `${item.serviceType}_${index}`;
  const serviceName = item.name.toLowerCase().replace(/\s+/g, '-');
  
  const configs = {
    // Compute
    vm: `resource "azurerm_linux_virtual_machine" "${resourceName}" {
  name                = "${serviceName}"
  resource_group_name = azurerm_resource_group.main.name
  location            = azurerm_resource_group.main.location
  size                = "Standard_B2s"
  admin_username      = "azureuser"
  
  network_interface_ids = [
    azurerm_network_interface.${resourceName}_nic.id,
  ]
  
  admin_ssh_key {
    username   = "azureuser"
    public_key = file("~/.ssh/id_rsa.pub")
  }
  
  os_disk {
    caching              = "ReadWrite"
    storage_account_type = "Standard_LRS"
  }
  
  source_image_reference {
    publisher = "Canonical"
    offer     = "0001-com-ubuntu-server-jammy"
    sku       = "22_04-lts"
    version   = "latest"
  }
  
  tags = {
    environment = "production"
    created_by  = "azure-architecture-designer"
  }
}

resource "azurerm_network_interface" "${resourceName}_nic" {
  name                = "${serviceName}-nic"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  
  ip_configuration {
    name                          = "internal"
    subnet_id                     = azurerm_subnet.main.id
    private_ip_address_allocation = "Dynamic"
  }
}`,

    vmss: `resource "azurerm_linux_virtual_machine_scale_set" "${resourceName}" {
  name                = "${serviceName}"
  resource_group_name = azurerm_resource_group.main.name
  location            = azurerm_resource_group.main.location
  sku                 = "Standard_B2s"
  instances           = 2
  admin_username      = "azureuser"
  
  admin_ssh_key {
    username   = "azureuser"
    public_key = file("~/.ssh/id_rsa.pub")
  }
  
  source_image_reference {
    publisher = "Canonical"
    offer     = "0001-com-ubuntu-server-jammy"
    sku       = "22_04-lts"
    version   = "latest"
  }
  
  os_disk {
    storage_account_type = "Standard_LRS"
    caching              = "ReadWrite"
  }
  
  network_interface {
    name    = "primary"
    primary = true
    
    ip_configuration {
      name      = "internal"
      primary   = true
      subnet_id = azurerm_subnet.main.id
    }
  }
}`,

    function: `resource "azurerm_storage_account" "${resourceName}_storage" {
  name                     = "${serviceName.replace(/-/g, '')}sa"
  resource_group_name      = azurerm_resource_group.main.name
  location                 = azurerm_resource_group.main.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_service_plan" "${resourceName}_plan" {
  name                = "${serviceName}-plan"
  resource_group_name = azurerm_resource_group.main.name
  location            = azurerm_resource_group.main.location
  os_type             = "Linux"
  sku_name            = "Y1"
}

resource "azurerm_linux_function_app" "${resourceName}" {
  name                = "${serviceName}"
  resource_group_name = azurerm_resource_group.main.name
  location            = azurerm_resource_group.main.location
  
  storage_account_name       = azurerm_storage_account.${resourceName}_storage.name
  storage_account_access_key = azurerm_storage_account.${resourceName}_storage.primary_access_key
  service_plan_id            = azurerm_service_plan.${resourceName}_plan.id
  
  site_config {}
}`,

    appservice: `resource "azurerm_service_plan" "${resourceName}_plan" {
  name                = "${serviceName}-plan"
  resource_group_name = azurerm_resource_group.main.name
  location            = azurerm_resource_group.main.location
  os_type             = "Linux"
  sku_name            = "B1"
}

resource "azurerm_linux_web_app" "${resourceName}" {
  name                = "${serviceName}"
  resource_group_name = azurerm_resource_group.main.name
  location            = azurerm_resource_group.main.location
  service_plan_id     = azurerm_service_plan.${resourceName}_plan.id
  
  site_config {
    always_on = false
  }
}`,

    aks: `resource "azurerm_kubernetes_cluster" "${resourceName}" {
  name                = "${serviceName}"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  dns_prefix          = "${serviceName}"
  
  default_node_pool {
    name       = "default"
    node_count = 2
    vm_size    = "Standard_B2s"
  }
  
  identity {
    type = "SystemAssigned"
  }
}`,

    // Storage
    storage: `resource "azurerm_storage_account" "${resourceName}" {
  name                     = "${serviceName.replace(/-/g, '')}sa"
  resource_group_name      = azurerm_resource_group.main.name
  location                 = azurerm_resource_group.main.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
  
  tags = {
    environment = "production"
  }
}`,

    // Databases
    sqldb: `resource "azurerm_mssql_server" "${resourceName}_server" {
  name                         = "${serviceName}-server"
  resource_group_name          = azurerm_resource_group.main.name
  location                     = azurerm_resource_group.main.location
  version                      = "12.0"
  administrator_login          = "sqladmin"
  administrator_login_password = "P@ssw0rd1234!"
}

resource "azurerm_mssql_database" "${resourceName}" {
  name      = "${serviceName}-db"
  server_id = azurerm_mssql_server.${resourceName}_server.id
  sku_name  = "Basic"
}`,

    cosmosdb: `resource "azurerm_cosmosdb_account" "${resourceName}" {
  name                = "${serviceName}"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  offer_type          = "Standard"
  kind                = "GlobalDocumentDB"
  
  consistency_policy {
    consistency_level = "Session"
  }
  
  geo_location {
    location          = azurerm_resource_group.main.location
    failover_priority = 0
  }
}`,

    // Networking
    vnet: `resource "azurerm_virtual_network" "${resourceName}" {
  name                = "${serviceName}"
  address_space       = ["10.0.0.0/16"]
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
}

resource "azurerm_subnet" "main" {
  name                 = "default"
  resource_group_name  = azurerm_resource_group.main.name
  virtual_network_name = azurerm_virtual_network.${resourceName}.name
  address_prefixes     = ["10.0.1.0/24"]
}`,

    loadbalancer: `resource "azurerm_public_ip" "${resourceName}_pip" {
  name                = "${serviceName}-pip"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  allocation_method   = "Static"
  sku                 = "Standard"
}

resource "azurerm_lb" "${resourceName}" {
  name                = "${serviceName}"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  sku                 = "Standard"
  
  frontend_ip_configuration {
    name                 = "PublicIPAddress"
    public_ip_address_id = azurerm_public_ip.${resourceName}_pip.id
  }
}`,

    // Security
    keyvault: `data "azurerm_client_config" "current" {}

resource "azurerm_key_vault" "${resourceName}" {
  name                = "${serviceName}"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  tenant_id           = data.azurerm_client_config.current.tenant_id
  sku_name            = "standard"
}`,

    // Monitoring
    monitor: `resource "azurerm_log_analytics_workspace" "${resourceName}" {
  name                = "${serviceName}"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  sku                 = "PerGB2018"
  retention_in_days   = 30
}`,

    appinsights: `resource "azurerm_application_insights" "${resourceName}" {
  name                = "${serviceName}"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  application_type    = "web"
}`
  };
  
  return configs[item.serviceType] || `# ${item.name} (${item.serviceType}) - Configuration not available`;
};

/**
 * Generate networking configuration
 */
const generateNetworkingConfig = (items) => {
  return `# Network Security Group
resource "azurerm_network_security_group" "main" {
  name                = "nsg-main"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  
  security_rule {
    name                       = "allow-ssh"
    priority                   = 100
    direction                  = "Inbound"
    access                     = "Allow"
    protocol                   = "Tcp"
    source_port_range          = "*"
    destination_port_range     = "22"
    source_address_prefix      = "*"
    destination_address_prefix = "*"
  }
}`;
};

/**
 * Generate output values
 */
const generateOutput = (item, index) => {
  const resourceName = `${item.serviceType}_${index}`;
  
  const outputs = {
    vm: `output "${resourceName}_ip" {
  value = azurerm_linux_virtual_machine.${resourceName}.private_ip_address
}`,
    storage: `output "${resourceName}_connection_string" {
  value     = azurerm_storage_account.${resourceName}.primary_connection_string
  sensitive = true
}`,
    sqldb: `output "${resourceName}_connection_string" {
  value     = azurerm_mssql_server.${resourceName}_server.fully_qualified_domain_name
  sensitive = true
}`,
    keyvault: `output "${resourceName}_uri" {
  value = azurerm_key_vault.${resourceName}.vault_uri
}`
  };
  
  return outputs[item.serviceType] || null;
};

/**
 * Download Terraform configuration as .tf file
 */
export const downloadTerraform = (items, connections) => {
  const config = generateTerraform(items, connections);
  const blob = new Blob([config], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `azure-architecture-${Date.now()}.tf`;
  link.click();
  URL.revokeObjectURL(url);
};
